### ISSUE TITLE
Webp Converter stopped working

### ISSUE THREAD

**Issue by Roshri** [ThePromidius/Manga-Manager#97]
**Describe the bug**
After a while of using it the Webp converted suddenly started to error out on every volume I tried to convert

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\CommandLineTools\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\roshr\Documents\WindowsPowerShell\MangaManager_v0.4.5\MangaManager\CommonLib\WebpConverter.py", line 339, in start
    self._process(cbzFilepath, self._tmpname)
  File "C:\Users\roshr\Documents\WindowsPowerShell\MangaManager_v0.4.5\MangaManager\CommonLib\WebpConverter.py", line 380, in _process
    zout.writestr(file_name + ".webp", convertToWebp(open_zipped_file))
  File "C:\Users\roshr\Documents\WindowsPowerShell\MangaManager_v0.4.5\MangaManager\CommonLib\WebpConverter.py", line 121, in convertToWebp
    image.save(converted_image, format="webp")
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 2178, in save
    self._ensure_mutable()
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 597, in _ensure_mutable
    self._copy()
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 590, in _copy
    self.load()
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\ImageFile.py", line 247, in load
    raise OSError(
OSError: image file is truncated (34 bytes not processed)
```

**To Reproduce**
1. Load a .cbz
2. Process
3. It errors out

**Additional context**
It may have something to do with dependency conflicts I had while updating other software through pip, which needed a higher version of Pillow? But then I decided to rollback and reinstalled from the requirements.txt

**Comment by ThePromidius** [comment]
seems to be some issue with the file. I will update to make it less prone to propagate errors (ignore corrupted files errors)
I don't really know how this will behave with such type of files if they won't be converted or if they won't be saved.
Please do keep the broken file to test at a later time or send it to me.

Thanks for the report.

**Comment by Roshri** [comment]
I ended up converting them manually with nconvert, but I think I have at least one file left that had the same issue. It's nsfw tho, where should I send it?

**Comment by ThePromidius** [comment]
feel free to send it to my public mail [thepromidiusyt@gmail.com](mailto:thepromidiusyt@gmail.com)

**Comment by ThePromidius** [comment]
The file you sent me today has a different error when i try to open it:
```
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration
```
Looked into the file and the issue might be the splicit encoding being defined in the file:
```xml
<?xml version='1.0' encoding='utf-8'?>
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
```

**Comment by ThePromidius** [comment]
[ee10609](https://github.com/ThePromidius/Manga-Manager/commit/ee106093eee587da5527172291b44e4a8d15a368)
Should deal with the broken encodign from the file "Case Closed"
As for the original error i still can't reproduce let me know again if you get the error again.

**Comment by Roshri** [comment]
Uh, weird, when I try with the Case Closed (even trying with the develop branch) this is the error it gives me 

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\CommandLineTools\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 339, in start
    self._process(cbzFilepath, self._tmpname)
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 380, in _process
    zout.writestr(file_name + ".webp", convertToWebp(open_zipped_file))
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 121, in convertToWebp
    image.save(converted_image, format="webp")
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 2178, in save
    self._ensure_mutable()
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 597, in _ensure_mutable
    self._copy()
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 590, in _copy
    self.load()
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\ImageFile.py", line 247, in load
    raise OSError(
OSError: image file is truncated (6 bytes not processed)
```
Which looks the same as the one I posted before. I'm sending you the first file I found with this issue as well as other file that also has utf-8 encoding defined in it's comicinfo.xml and was proccessed without issues

**Comment by ThePromidius** [comment]
Ok i can confirm that i'm dumb af.
This time i actually tried using webp converter. I don't even know why i even tried to open with metadata editor in the first place, but hey! we found a different bug there so guess it's good.

Back to the issue this time i opened it with webp converter and managed to replicate. As i though it's the image missing some blocks of data. I adjusted the library i use to be tolerant with these types of images and use what it's available.
[e4e318a](https://github.com/ThePromidius/Manga-Manager/commit/e4e318a5d1bd22cdfd8b99ece81cbd68ea3b30ce) does fix it for me. 
Let me know if you have further issues.

**Comment by Roshri** [comment]
This seems to fix the issue! Thanks for the quick fix!
I tried the develop branch in a few more files and found a new error I haven't seen before

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\CommandLineTools\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 344, in start
    self._process(cbzFilepath, self._tmpname)
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 387, in _process
    zout.writestr(file_name + ".webp", convertToWebp(open_zipped_file))
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 125, in convertToWebp
    image.save(converted_image, format="webp")
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\WebPImagePlugin.py", line 327, in _save
    data = _webp.WebPEncode(
ValueError: encoding error 5
```
This time it happened on some webtoons, with the long strip format. There seems to be an issue with the picture because YACReader can't render it either, but if I open the archive with 7zip and manually open it with an image viewer software (XnViewMP in this case) it works just fine.
Sending you this file too. I thought it was light enough for github, but I guess I was wrong lol

**Comment by Roshri** [comment]
Found another weird issue, but it's easy to fix from the user side. If for some reason the .cbz has a ''__MACOSX'' folder, the program will crash upon finding it. Since I'm on Windows it was as easy as deleting every '__MACOSX''  folder from my files, but maybe the program can just skip it? The file itself can be found on the cat site

```
2022-10-29 11:46:41,875 - CommonLib.WebpConverter - INFO - Processed 'Saint Young Men v02 (2200h) [Rurika] (Kodansha).cbz'
2022-10-29 11:46:41,878 - CommonLib.WebpConverter - INFO - Processing 'V:/Manga/Translated/Ongoing/Saint Young Men/Saint Young Men v03(Me).cbz'
2022-10-29 11:46:41,916 - CommonLib.WebpConverter - DEBUG - processing 'cover.jpeg'
2022-10-29 11:46:41,932 - CommonLib.WebpConverter - DEBUG - Successfully converted image to webp
2022-10-29 11:46:42,202 - CommonLib.WebpConverter - DEBUG - Successfully converted image to webp
2022-10-29 11:46:42,229 - CommonLib.WebpConverter - DEBUG - Added converted to webp file 'cover.jpeg' to new file
2022-10-29 11:46:42,229 - CommonLib.WebpConverter - DEBUG - processing '__MACOSX/._cover.jpeg'
2022-10-29 11:46:42,230 - CommonLib.WebpConverter - DEBUG - Successfully converted image to webp
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\CommandLineTools\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 344, in start
    self._process(cbzFilepath, self._tmpname)
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 387, in _process
    zout.writestr(file_name + ".webp", convertToWebp(open_zipped_file))
  File "C:\Users\roshr\Documents\WindowsPowerShell\Manga-Manager-develop\MangaManager\CommonLib\WebpConverter.py", line 121, in convertToWebp
    image = Image.open(open_zipped_file)
  File "C:\CommandLineTools\Python\Python310\lib\site-packages\PIL\Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <zipfile.ZipExtFile name='__MACOSX/._cover.jpeg' mode='r' compress_type=deflate>
```

**Comment by ThePromidius** [comment]
I can prob add something to skip it.
Also, please do create different issues for unrelated bugs.
Makes tracking easier 😉

**Comment by Roshri** [comment]
Oh, my bad, sorry for the trouble!
Then the first issue was solved
